name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 9.0.0
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install

            - name: Generate Prisma Client
              run: pnpm prisma:generate

            - name: Restore turbo cache
              uses: actions/cache@v3
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-${{ github.job }}-${{ github.ref_name }}-
                      ${{ runner.os }}-turbo-${{ github.job }}- 
                      ${{ runner.os }}-turbo-

            - name: Lint Code
              run: pnpm run lint:ci

            - name: Build Application
              run: pnpm run build

            - name: Upload dist artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: |
                      apps/*/dist
                      packages/*/dist
